---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: awxtaskconfigoverrides.awx.ansible.com
spec:
  group: awx.ansible.com
  names:
    kind: AWXTaskConfigOverride
    listKind: AWXTaskConfigOverrideList
    plural: awxtaskconfigoverrides
    singular: awxtaskconfigoverride
  scope: Namespaced
  versions:
  - name: v1beta1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        description: Schema validation for the AWXTaskConfigOverride CRD
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            required:
              - awx_name
            properties:
              awx_name:
                type: string
              task_privileged:
                description: If a privileged security context should be enabled
                type: boolean
              extra_volumes:
                description: Specify extra volumes to add to the task pod
                type: string
              node_selector:
                description: nodeSelector for the pods
                type: string
              topology_spread_constraints:
                description: topology rule(s) for the pods
                type: string
              annotations:
                description: annotations for the pods
                type: string
              tolerations:
                description: node tolerations for the pods
                type: string
              image:
                description: Registry path to the application container to use
                type: string
              image_version:
                description: Application container image version to use
                type: string
              ee_images:
                description: Registry path to the Execution Environment container to use
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    image:
                      type: string
              control_plane_ee_image:
                description: Registry path to the Execution Environment container image to use on control plane pods
                type: string
              control_plane_priority_class:
                description: Assign a preexisting priority class to the control plane pods
                type: string
              ee_pull_credentials_secret:
                description: Secret where pull credentials for registered ees can be found
                type: string
              image_pull_policy:
                description: The image pull policy
                type: string
                default: IfNotPresent
                enum:
                - Always
                - always
                - Never
                - never
                - IfNotPresent
                - ifnotpresent
              image_pull_secrets:
                description: Image pull secrets for app and database containers
                type: array
                items:
                  type: string
              task_resource_requirements:
                description: Resource requirements for the task container
                properties:
                  requests:
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
                      storage:
                        type: string
                    type: object
                  limits:
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
                      storage:
                        type: string
                    type: object
                type: object
              ee_resource_requirements:
                description: Resource requirements for the ee container
                properties:
                  requests:
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
                      storage:
                        type: string
                    type: object
                  limits:
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
                      storage:
                        type: string
                    type: object
                type: object
              redis_resource_requirements:
                description: Resource requirements for the redis container
                properties:
                  requests:
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
                      storage:
                        type: string
                    type: object
                  limits:
                    properties:
                      cpu:
                        type: string
                      memory:
                        type: string
                      storage:
                        type: string
                    type: object
                type: object
              replicas:
                description: Number of task instance replicas
                type: integer
                format: int32
              task_args:
                type: array
                items:
                  type: string
              task_command:
                type: array
                items:
                  type: string
              task_extra_env:
                type: string
              ee_extra_env:
                type: string
              ee_extra_volume_mounts:
                description: Specify volume mounts to be added to Execution container
                type: string
              task_extra_volume_mounts:
                description: Specify volume mounts to be added to Task container
                type: string
              redis_image:
                description: Registry path to the redis container to use
                type: string
              redis_image_version:
                description: Redis container image version to use
                type: string
              redis_capabilities:
                description: Redis container capabilities
                type: array
                items:
                  type: string
              init_container_image:
                description: Registry path to the init container to use
                type: string
              init_container_image_version:
                description: Init container image version to use
                type: string
              init_container_extra_commands:
                description: Extra commands for the init container
                type: string
              init_container_extra_volume_mounts:
                description: Specify volume mounts to be added to the init container
                type: string
              extra_settings:
                description: Extra settings to specify for the API
                items:
                  properties:
                    setting:
                      type: string
                    value:
                      x-kubernetes-preserve-unknown-fields: true
                  type: object
                type: array
              security_context_settings:
                description: Key/values that will be set under the pod-level securityContext field
                type: object
                x-kubernetes-preserve-unknown-fields: true
            type: object
        type: object
