---

name: Devel

on:
  push:
    branches: [devel, pi]

jobs:
  release:
    runs-on: ubuntu-latest
    name: Push devel image
    steps:
      - uses: actions/checkout@v3

      # setup qemu and buildx
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get python version from Makefile
        run: echo py_version=`make PYTHON_VERSION` >> $GITHUB_ENV

      - name: Set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Install python ${{ env.py_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.py_version }}

      - name: Log in to registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Image
        run: |
          IMG=ghcr.io/${OWNER_LC}/awx-operator:${GITHUB_REF##*/} make docker-build

      #- name: Push development images
      #  run: |
      #    docker push ghcr.io/${OWNER_LC}/awx-operator:${GITHUB_REF##*/}
